WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/10
2023-04-04 12:46:42.430052: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-04 12:46:42.430498: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-04 12:46:42.460350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-04 12:46:42.461666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-04 12:46:42.462894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-04 12:46:42.465744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-04 12:46:42.497484: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.031ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-04 12:46:42.760573: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-04 12:46:46.382648: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 5s - loss: 0.5010 - accuracy: 0.8015 - auc: 0.5476 - precision: 0.2281 - recall: 0.0460 - balanced_accuracy: 0.5062 - val_loss: 0.4368 - val_accuracy: 0.8218 - val_auc: 0.6948 - val_precision: 1.0000 - val_recall: 0.0047 - val_balanced_accuracy: 0.5019
Epoch 2/10
37/37 - 0s - loss: 0.4776 - accuracy: 0.8150 - auc: 0.5859 - precision: 0.3739 - recall: 0.0508 - balanced_accuracy: 0.5169 - val_loss: 0.4186 - val_accuracy: 0.8311 - val_auc: 0.7291 - val_precision: 0.9286 - val_recall: 0.0613 - val_balanced_accuracy: 0.5330
Epoch 3/10
37/37 - 0s - loss: 0.4593 - accuracy: 0.8173 - auc: 0.6317 - precision: 0.4286 - recall: 0.0638 - balanced_accuracy: 0.5219 - val_loss: 0.4064 - val_accuracy: 0.8454 - val_auc: 0.7426 - val_precision: 0.9394 - val_recall: 0.1462 - val_balanced_accuracy: 0.5705
Epoch 4/10
37/37 - 0s - loss: 0.4431 - accuracy: 0.8222 - auc: 0.6686 - precision: 0.5152 - recall: 0.1004 - balanced_accuracy: 0.5391 - val_loss: 0.3976 - val_accuracy: 0.8514 - val_auc: 0.7529 - val_precision: 0.9500 - val_recall: 0.1792 - val_balanced_accuracy: 0.5880
Epoch 5/10
37/37 - 0s - loss: 0.4280 - accuracy: 0.8334 - auc: 0.6957 - precision: 0.6576 - recall: 0.1429 - balanced_accuracy: 0.5626 - val_loss: 0.3912 - val_accuracy: 0.8514 - val_auc: 0.7603 - val_precision: 0.9091 - val_recall: 0.1887 - val_balanced_accuracy: 0.5928
Epoch 6/10
37/37 - 0s - loss: 0.4187 - accuracy: 0.8363 - auc: 0.7136 - precision: 0.6538 - recall: 0.1806 - balanced_accuracy: 0.5788 - val_loss: 0.3859 - val_accuracy: 0.8530 - val_auc: 0.7660 - val_precision: 0.9130 - val_recall: 0.1981 - val_balanced_accuracy: 0.5968
Epoch 7/10
37/37 - 0s - loss: 0.4122 - accuracy: 0.8397 - auc: 0.7276 - precision: 0.6880 - recall: 0.1901 - balanced_accuracy: 0.5851 - val_loss: 0.3817 - val_accuracy: 0.8539 - val_auc: 0.7714 - val_precision: 0.8679 - val_recall: 0.2170 - val_balanced_accuracy: 0.6090
Epoch 8/10
37/37 - 0s - loss: 0.4016 - accuracy: 0.8441 - auc: 0.7435 - precision: 0.7224 - recall: 0.2090 - balanced_accuracy: 0.5933 - val_loss: 0.3789 - val_accuracy: 0.8522 - val_auc: 0.7744 - val_precision: 0.8364 - val_recall: 0.2170 - val_balanced_accuracy: 0.6080
Epoch 9/10
37/37 - 0s - loss: 0.3943 - accuracy: 0.8450 - auc: 0.7547 - precision: 0.7116 - recall: 0.2243 - balanced_accuracy: 0.6022 - val_loss: 0.3756 - val_accuracy: 0.8505 - val_auc: 0.7791 - val_precision: 0.7778 - val_recall: 0.2311 - val_balanced_accuracy: 0.6123
Epoch 10/10
INFO     Computation time for training the single-label model for AR: 0.16 min
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, model, target, opts.outputDir, drop_values=True, threshold=10, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 26, in shap_explain
    tf.keras.utils.plot_model(model, show_shapes=True, rankdir="LR")
NameError: name 'tf' is not defined
37/37 - 0s - loss: 0.3971 - accuracy: 0.8433 - auc: 0.7489 - precision: 0.6966 - recall: 0.2196 - balanced_accuracy: 0.5973 - val_loss: 0.3732 - val_accuracy: 0.8505 - val_auc: 0.7833 - val_precision: 0.7612 - val_recall: 0.2406 - val_balanced_accuracy: 0.6152
Epoch 00010: val_loss improved from inf to 0.37320, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
<IPython.core.display.HTML object>
('You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) ', 'for plot_model/model_to_dot to work.')
[ True  True  True ...  True  True  True]
<bound method Model.predict of <keras.engine.sequential.Sequential object at 0x2b9d6ede37f0>>
[[0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>	4735
<class 'tuple'>	2