WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
2023-04-04 13:05:04.027482: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-04 13:05:04.027873: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-04 13:05:04.044909: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-04 13:05:04.045888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-04 13:05:04.046823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-04 13:05:04.048280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-04 13:05:04.082138: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.041ms.
  function_optimizer: function_optimizer did nothing. time = 0.002ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-04 13:05:04.336883: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
2023-04-04 13:05:10.514972: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 7s - loss: 0.4912 - accuracy: 0.8137 - auc: 0.5534 - precision: 0.2989 - recall: 0.0307 - balanced_accuracy: 0.5078 - val_loss: 0.4413 - val_accuracy: 0.8302 - val_auc: 0.6431 - val_precision: 0.9231 - val_recall: 0.0566 - val_balanced_accuracy: 0.5297
Epoch 2/10
37/37 - 0s - loss: 0.4724 - accuracy: 0.8203 - auc: 0.5983 - precision: 0.4841 - recall: 0.0720 - balanced_accuracy: 0.5283 - val_loss: 0.4243 - val_accuracy: 0.8404 - val_auc: 0.7036 - val_precision: 0.8966 - val_recall: 0.1226 - val_balanced_accuracy: 0.5616
Epoch 3/10
37/37 - 0s - loss: 0.4485 - accuracy: 0.8241 - auc: 0.6557 - precision: 0.5402 - recall: 0.1110 - balanced_accuracy: 0.5468 - val_loss: 0.4123 - val_accuracy: 0.8412 - val_auc: 0.7313 - val_precision: 0.8333 - val_recall: 0.1415 - val_balanced_accuracy: 0.5690
Epoch 4/10
37/37 - 0s - loss: 0.4426 - accuracy: 0.8294 - auc: 0.6623 - precision: 0.6077 - recall: 0.1299 - balanced_accuracy: 0.5567 - val_loss: 0.4044 - val_accuracy: 0.8387 - val_auc: 0.7460 - val_precision: 0.7442 - val_recall: 0.1509 - val_balanced_accuracy: 0.5711
Epoch 5/10
37/37 - 0s - loss: 0.4284 - accuracy: 0.8374 - auc: 0.6896 - precision: 0.6711 - recall: 0.1783 - balanced_accuracy: 0.5786 - val_loss: 0.3977 - val_accuracy: 0.8370 - val_auc: 0.7572 - val_precision: 0.7021 - val_recall: 0.1557 - val_balanced_accuracy: 0.5714
Epoch 6/10
37/37 - 0s - loss: 0.4152 - accuracy: 0.8408 - auc: 0.7149 - precision: 0.7048 - recall: 0.1889 - balanced_accuracy: 0.5845 - val_loss: 0.3925 - val_accuracy: 0.8370 - val_auc: 0.7640 - val_precision: 0.6939 - val_recall: 0.1604 - val_balanced_accuracy: 0.5714
Epoch 7/10
37/37 - 0s - loss: 0.4115 - accuracy: 0.8401 - auc: 0.7207 - precision: 0.6875 - recall: 0.1948 - balanced_accuracy: 0.5859 - val_loss: 0.3883 - val_accuracy: 0.8387 - val_auc: 0.7705 - val_precision: 0.6981 - val_recall: 0.1745 - val_balanced_accuracy: 0.5770
Epoch 8/10
37/37 - 0s - loss: 0.4032 - accuracy: 0.8429 - auc: 0.7355 - precision: 0.6929 - recall: 0.2184 - balanced_accuracy: 0.5998 - val_loss: 0.3836 - val_accuracy: 0.8429 - val_auc: 0.7757 - val_precision: 0.7407 - val_recall: 0.1887 - val_balanced_accuracy: 0.5847
Epoch 9/10
INFO     Computation time for training the single-label model for AR: 0.21 min
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 550, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 421, in fit_and_evaluate_model
    sd.shap_explain(x_train, model, target, opts.outputDir, drop_values=True, threshold=10, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 26, in shap_explain
    tf.keras.utils.plot_model(model, show_shapes=True, rankdir="LR")
NameError: name 'tf' is not defined
37/37 - 0s - loss: 0.3972 - accuracy: 0.8488 - auc: 0.7474 - precision: 0.7589 - recall: 0.2267 - balanced_accuracy: 0.6060 - val_loss: 0.3805 - val_accuracy: 0.8463 - val_auc: 0.7811 - val_precision: 0.7500 - val_recall: 0.2123 - val_balanced_accuracy: 0.5985
Epoch 10/10
37/37 - 0s - loss: 0.3906 - accuracy: 0.8477 - auc: 0.7561 - precision: 0.7172 - recall: 0.2456 - balanced_accuracy: 0.6124 - val_loss: 0.3771 - val_accuracy: 0.8488 - val_auc: 0.7854 - val_precision: 0.7463 - val_recall: 0.2358 - val_balanced_accuracy: 0.6081
Epoch 00010: val_loss improved from inf to 0.37711, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
<IPython.core.display.HTML object>
[ True  True  True ...  True  True  True]
<bound method Model.predict of <keras.engine.sequential.Sequential object at 0x2b38d12e9850>>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>	4735
<class 'tuple'>	2