WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
2023-04-26 13:07:58.338688: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-26 13:07:58.338976: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-26 13:07:58.407042: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-26 13:07:58.408799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-26 13:07:58.410294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-26 13:07:58.414033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-26 13:07:58.447964: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.058ms.
  function_optimizer: function_optimizer did nothing. time = 0.003ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-26 13:07:58.706504: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
37/37 - 7s - loss: 0.4862 - accuracy: 0.8095 - auc: 0.5718 - precision: 0.3203 - recall: 0.0579 - balanced_accuracy: 0.5156 - val_loss: 0.4488 - val_accuracy: 0.8269 - val_auc: 0.6262 - val_precision: 1.0000 - val_recall: 0.0330 - val_balanced_accuracy: 0.5190
Epoch 2/10
37/37 - 0s - loss: 0.4681 - accuracy: 0.8196 - auc: 0.6088 - precision: 0.4679 - recall: 0.0602 - balanced_accuracy: 0.5229 - val_loss: 0.4308 - val_accuracy: 0.8387 - val_auc: 0.6738 - val_precision: 0.9565 - val_recall: 0.1038 - val_balanced_accuracy: 0.5548
2023-04-26 13:08:05.648540: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
Epoch 3/10
37/37 - 0s - loss: 0.4494 - accuracy: 0.8245 - auc: 0.6491 - precision: 0.5513 - recall: 0.1015 - balanced_accuracy: 0.5422 - val_loss: 0.4198 - val_accuracy: 0.8395 - val_auc: 0.6965 - val_precision: 0.8929 - val_recall: 0.1179 - val_balanced_accuracy: 0.5595
Epoch 4/10
37/37 - 0s - loss: 0.4303 - accuracy: 0.8315 - auc: 0.6878 - precision: 0.6601 - recall: 0.1192 - balanced_accuracy: 0.5536 - val_loss: 0.4111 - val_accuracy: 0.8412 - val_auc: 0.7177 - val_precision: 0.8750 - val_recall: 0.1321 - val_balanced_accuracy: 0.5652
Epoch 5/10
37/37 - 1s - loss: 0.4215 - accuracy: 0.8359 - auc: 0.7028 - precision: 0.6786 - recall: 0.1570 - balanced_accuracy: 0.5682 - val_loss: 0.4044 - val_accuracy: 0.8463 - val_auc: 0.7313 - val_precision: 0.8750 - val_recall: 0.1651 - val_balanced_accuracy: 0.5815
Epoch 6/10
37/37 - 0s - loss: 0.4130 - accuracy: 0.8386 - auc: 0.7269 - precision: 0.6694 - recall: 0.1936 - balanced_accuracy: 0.5836 - val_loss: 0.3986 - val_accuracy: 0.8471 - val_auc: 0.7422 - val_precision: 0.8780 - val_recall: 0.1698 - val_balanced_accuracy: 0.5838
Epoch 7/10
37/37 - 0s - loss: 0.4014 - accuracy: 0.8454 - auc: 0.7417 - precision: 0.7578 - recall: 0.1995 - balanced_accuracy: 0.5918 - val_loss: 0.3944 - val_accuracy: 0.8471 - val_auc: 0.7487 - val_precision: 0.8605 - val_recall: 0.1745 - val_balanced_accuracy: 0.5855
Epoch 8/10
37/37 - 1s - loss: 0.3915 - accuracy: 0.8513 - auc: 0.7530 - precision: 0.7871 - recall: 0.2314 - balanced_accuracy: 0.6092 - val_loss: 0.3903 - val_accuracy: 0.8463 - val_auc: 0.7572 - val_precision: 0.8261 - val_recall: 0.1792 - val_balanced_accuracy: 0.5846
Epoch 9/10
37/37 - 0s - loss: 0.3874 - accuracy: 0.8496 - auc: 0.7691 - precision: 0.7547 - recall: 0.2361 - balanced_accuracy: 0.6099 - val_loss: 0.3871 - val_accuracy: 0.8463 - val_auc: 0.7628 - val_precision: 0.7679 - val_recall: 0.2028 - val_balanced_accuracy: 0.5982
Epoch 10/10
37/37 - 0s - loss: 0.3816 - accuracy: 0.8543 - auc: 0.7744 - precision: 0.7698 - recall: 0.2645 - balanced_accuracy: 0.6241 - val_loss: 0.3843 - val_accuracy: 0.8471 - val_auc: 0.7665 - val_precision: 0.7719 - val_recall: 0.2075 - val_balanced_accuracy: 0.6012
Epoch 00010: val_loss improved from inf to 0.38427, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
<IPython.core.display.HTML object>
[ True  True  True ...  True  True  True]
<bound method Model.predict of <keras.engine.sequential.Sequential object at 0x2b53ec65b820>>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>	4735
INFO     Computation time for training the single-label model for AR: 0.24 min
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, x_test, model, target, opts.outputDir, drop_values=True, threshold=100, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 26, in shap_explain
    print(f"{type(x_include_labels)}\t{len(x_include_labels[2])}")
IndexError: tuple index out of range