WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
2023-04-04 12:42:48.726624: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-04 12:42:48.726852: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-04 12:42:48.771706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-04 12:42:48.772675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-04 12:42:48.773722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-04 12:42:48.774671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-04 12:42:48.800806: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.036ms.
  function_optimizer: function_optimizer did nothing. time = 0.002ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-04 12:42:49.080869: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
2023-04-04 12:42:52.657509: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 5s - loss: 0.5029 - accuracy: 0.8161 - auc: 0.5050 - precision: 0.2391 - recall: 0.0130 - balanced_accuracy: 0.5024 - val_loss: 0.4606 - val_accuracy: 0.8209 - val_auc: 0.5980 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_balanced_accuracy: 0.5000
Epoch 2/10
37/37 - 0s - loss: 0.4755 - accuracy: 0.8180 - auc: 0.5817 - precision: 0.4194 - recall: 0.0460 - balanced_accuracy: 0.5149 - val_loss: 0.4414 - val_accuracy: 0.8243 - val_auc: 0.6698 - val_precision: 1.0000 - val_recall: 0.0189 - val_balanced_accuracy: 0.5090
Epoch 3/10
37/37 - 0s - loss: 0.4564 - accuracy: 0.8220 - auc: 0.6329 - precision: 0.5192 - recall: 0.0638 - balanced_accuracy: 0.5262 - val_loss: 0.4296 - val_accuracy: 0.8361 - val_auc: 0.6988 - val_precision: 0.9500 - val_recall: 0.0896 - val_balanced_accuracy: 0.5486
Epoch 4/10
37/37 - 0s - loss: 0.4406 - accuracy: 0.8253 - auc: 0.6728 - precision: 0.5602 - recall: 0.1098 - balanced_accuracy: 0.5456 - val_loss: 0.4225 - val_accuracy: 0.8361 - val_auc: 0.7066 - val_precision: 0.8750 - val_recall: 0.0991 - val_balanced_accuracy: 0.5514
Epoch 5/10
37/37 - 0s - loss: 0.4275 - accuracy: 0.8397 - auc: 0.6884 - precision: 0.7558 - recall: 0.1535 - balanced_accuracy: 0.5694 - val_loss: 0.4167 - val_accuracy: 0.8370 - val_auc: 0.7191 - val_precision: 0.8276 - val_recall: 0.1132 - val_balanced_accuracy: 0.5614
Epoch 6/10
37/37 - 0s - loss: 0.4156 - accuracy: 0.8384 - auc: 0.7156 - precision: 0.6814 - recall: 0.1818 - balanced_accuracy: 0.5818 - val_loss: 0.4114 - val_accuracy: 0.8395 - val_auc: 0.7285 - val_precision: 0.8056 - val_recall: 0.1368 - val_balanced_accuracy: 0.5719
Epoch 7/10
37/37 - 0s - loss: 0.4120 - accuracy: 0.8399 - auc: 0.7216 - precision: 0.7051 - recall: 0.1806 - balanced_accuracy: 0.5808 - val_loss: 0.4073 - val_accuracy: 0.8404 - val_auc: 0.7370 - val_precision: 0.7674 - val_recall: 0.1557 - val_balanced_accuracy: 0.5836
INFO     Computation time for training the single-label model for AR: 0.16 min
Epoch 8/10
37/37 - 0s - loss: 0.3949 - accuracy: 0.8509 - auc: 0.7500 - precision: 0.7831 - recall: 0.2302 - balanced_accuracy: 0.6114 - val_loss: 0.4041 - val_accuracy: 0.8404 - val_auc: 0.7423 - val_precision: 0.7447 - val_recall: 0.1651 - val_balanced_accuracy: 0.5874
Epoch 9/10
37/37 - 0s - loss: 0.3887 - accuracy: 0.8505 - auc: 0.7619 - precision: 0.7747 - recall: 0.2314 - balanced_accuracy: 0.6060 - val_loss: 0.4008 - val_accuracy: 0.8387 - val_auc: 0.7465 - val_precision: 0.7059 - val_recall: 0.1698 - val_balanced_accuracy: 0.5878
Epoch 10/10
37/37 - 0s - loss: 0.3813 - accuracy: 0.8513 - auc: 0.7752 - precision: 0.7581 - recall: 0.2479 - balanced_accuracy: 0.6148 - val_loss: 0.3979 - val_accuracy: 0.8378 - val_auc: 0.7535 - val_precision: 0.6724 - val_recall: 0.1840 - val_balanced_accuracy: 0.5916
Epoch 00010: val_loss improved from inf to 0.39794, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
<IPython.core.display.HTML object>
[ True  True  True ...  True  True  True]
<bound method Model.predict of <keras.engine.sequential.Sequential object at 0x2b048967e820>>
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>	4735
<class 'tuple'>	2
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, model, target, opts.outputDir, drop_values=True, threshold=10, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 26, in shap_explain
    explainer = shap.explainers.GPUTree(model, data=x_train)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_tree.py", line 149, in __init__
    self.model = TreeEnsemble(model, self.data, self.data_missing, model_output)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_tree.py", line 993, in __init__
    raise InvalidModelError("Model type not yet supported by TreeExplainer: " + str(type(model)))
shap.utils._exceptions.InvalidModelError: Model type not yet supported by TreeExplainer: <class 'keras.engine.sequential.Sequential'>