WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
WARNING  `period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
Epoch 1/10
2023-04-03 13:40:17.998468: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 4
2023-04-03 13:40:17.998718: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2023-04-03 13:40:18.015895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78600 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0
2023-04-03 13:40:18.016868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 78600 MB memory:  -> device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0
2023-04-03 13:40:18.017779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 78600 MB memory:  -> device: 2, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0
2023-04-03 13:40:18.018684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 78600 MB memory:  -> device: 3, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:e3:00.0, compute capability: 8.0
2023-04-03 13:40:18.049347: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.033ms.
  function_optimizer: function_optimizer did nothing. time = 0.002ms.
WARNING:tensorflow:From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
WARNING  From /home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:3777: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
2023-04-03 13:40:18.310384: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-03 13:40:24.109740: I tensorflow/stream_executor/cuda/cuda_blas.cc:1760] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
37/37 - 7s - loss: 0.5100 - accuracy: 0.8025 - auc: 0.5102 - precision: 0.1562 - recall: 0.0236 - balanced_accuracy: 0.4983 - val_loss: 0.4635 - val_accuracy: 0.8209 - val_auc: 0.5764 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_balanced_accuracy: 0.5000
Epoch 2/10
37/37 - 0s - loss: 0.4884 - accuracy: 0.8144 - auc: 0.5639 - precision: 0.3596 - recall: 0.0484 - balanced_accuracy: 0.5156 - val_loss: 0.4444 - val_accuracy: 0.8209 - val_auc: 0.6396 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_balanced_accuracy: 0.5000
Epoch 3/10
37/37 - 0s - loss: 0.4704 - accuracy: 0.8188 - auc: 0.6014 - precision: 0.4545 - recall: 0.0649 - balanced_accuracy: 0.5253 - val_loss: 0.4305 - val_accuracy: 0.8370 - val_auc: 0.6695 - val_precision: 1.0000 - val_recall: 0.0896 - val_balanced_accuracy: 0.5480
Epoch 4/10
37/37 - 0s - loss: 0.4478 - accuracy: 0.8222 - auc: 0.6579 - precision: 0.5175 - recall: 0.0874 - balanced_accuracy: 0.5357 - val_loss: 0.4210 - val_accuracy: 0.8471 - val_auc: 0.6911 - val_precision: 1.0000 - val_recall: 0.1462 - val_balanced_accuracy: 0.5741
Epoch 5/10
37/37 - 0s - loss: 0.4346 - accuracy: 0.8317 - auc: 0.6809 - precision: 0.6389 - recall: 0.1358 - balanced_accuracy: 0.5587 - val_loss: 0.4126 - val_accuracy: 0.8471 - val_auc: 0.7070 - val_precision: 0.9189 - val_recall: 0.1604 - val_balanced_accuracy: 0.5789
Epoch 6/10
37/37 - 0s - loss: 0.4271 - accuracy: 0.8367 - auc: 0.6990 - precision: 0.6682 - recall: 0.1736 - balanced_accuracy: 0.5790 - val_loss: 0.4069 - val_accuracy: 0.8463 - val_auc: 0.7174 - val_precision: 0.8571 - val_recall: 0.1698 - val_balanced_accuracy: 0.5881
Epoch 7/10
37/37 - 0s - loss: 0.4182 - accuracy: 0.8361 - auc: 0.7175 - precision: 0.6461 - recall: 0.1854 - balanced_accuracy: 0.5821 - val_loss: 0.4026 - val_accuracy: 0.8454 - val_auc: 0.7254 - val_precision: 0.8222 - val_recall: 0.1745 - val_balanced_accuracy: 0.5897
Epoch 8/10
37/37 - 0s - loss: 0.4080 - accuracy: 0.8399 - auc: 0.7347 - precision: 0.6718 - recall: 0.2054 - balanced_accuracy: 0.5933 - val_loss: 0.3983 - val_accuracy: 0.8463 - val_auc: 0.7344 - val_precision: 0.7885 - val_recall: 0.1934 - val_balanced_accuracy: 0.5965
Epoch 9/10
37/37 - 0s - loss: 0.4014 - accuracy: 0.8454 - auc: 0.7451 - precision: 0.7237 - recall: 0.2196 - balanced_accuracy: 0.5999 - val_loss: 0.3944 - val_accuracy: 0.8480 - val_auc: 0.7421 - val_precision: 0.7667 - val_recall: 0.2170 - val_balanced_accuracy: 0.6063
Epoch 10/10
37/37 - 0s - loss: 0.3949 - accuracy: 0.8475 - auc: 0.7565 - precision: 0.7306 - recall: 0.2338 - balanced_accuracy: 0.6092 - val_loss: 0.3911 - val_accuracy: 0.8480 - val_auc: 0.7486 - val_precision: 0.7581 - val_recall: 0.2217 - val_balanced_accuracy: 0.6075
Epoch 00010: val_loss improved from inf to 0.39111, saving model to /home/zadubrov/output/results_train/AR_single-labeled_Fold-0.model.weights.hdf5
<IPython.core.display.HTML object>
INFO     Computation time for training the single-label model for AR: 0.2 min
Traceback (most recent call last):
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 415, in <module>
    main()
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 392, in main
    train(fixed_opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/__main__.py", line 190, in train
    sl.train_single_label_models(df=df, opts=opts)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 551, in train_single_label_models
    performance = fit_and_evaluate_model(x_train=x_train, x_test=x_test, y_train=y_train, y_test=y_test,
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/single_label_model.py", line 422, in fit_and_evaluate_model
    sd.shap_explain(x_train, model, target, opts.outputDir, drop_values=True, threshold=10, save_values=True)
  File "/gpfs0/home/zadubrov/deepFPlearn_exai/dfpl/shap_dfpl.py", line 20, in shap_explain
    shap_values = explainer(x_train_to_explain)
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_permutation.py", line 82, in __call__
    return super().__call__(
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_explainer.py", line 266, in __call__
    row_result = self.explain_row(
  File "/home/zadubrov/.conda/envs/dfpl_exai/lib/python3.9/site-packages/shap/explainers/_permutation.py", line 164, in explain_row
    raise ValueError(f"max_evals={max_evals} is too low for the Permutation explainer, it must be at least 2 * num_features + 1 = {2 * len(inds) + 1}!")
ValueError: max_evals=500 is too low for the Permutation explainer, it must be at least 2 * num_features + 1 = 2003!